import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

/**
 * Contrast guards for the design tokens.
 *
 * The design calls these floors non-negotiable and they are trivial to break
 * with a plausible-looking edit — lightening a border because it "looks heavy",
 * dropping a label to the next step down because it "reads loud". Nothing in
 * the type system or the linter notices. This does.
 *
 * The palettes are parsed out of `globals.css` rather than duplicated here, so
 * a token can only be changed in one place. Duplicating them would let the
 * test keep passing against values the app no longer uses.
 */

// Resolved from the working directory rather than `import.meta.url`: these
// tests run under jsdom, where module URLs are `http:` and cannot be converted
// to a path.
const CSS = readFileSync(resolve(process.cwd(), "src/app/globals.css"), "utf8");

/**
 * Pulls one `--flume-*: #hex` palette out of a CSS block.
 *
 * @param header - The selector introducing the block, as written in the file.
 * @returns Token name (without the `--flume-` prefix) to hex.
 */
function palette(header: string): Record<string, string> {
  const start = CSS.indexOf(header);
  expect(start, `no \`${header}\` block in globals.css`).toBeGreaterThan(-1);

  const body = CSS.slice(start + header.length);
  const end = body.indexOf("\n}");
  const block = body.slice(0, end);

  const out: Record<string, string> = {};
  for (const [, name, hex] of block.matchAll(
    /--flume-([a-z0-9-]+):\s*(#[0-9a-f]{6})\s*;/g,
  )) {
    out[name] = hex;
  }
  return out;
}

const DARK = palette(":root {");
const LIGHT = palette(':root[data-theme="light"] {');

/**
 * WCAG 2.1 relative luminance.
 *
 * @param hex - A six-digit sRGB hex colour.
 * @returns Relative luminance in `0..=1`.
 */
function luminance(hex: string): number {
  const channels = [1, 3, 5].map((i) => {
    const c = parseInt(hex.slice(i, i + 2), 16) / 255;
    return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  });
  return 0.2126 * channels[0] + 0.7152 * channels[1] + 0.0722 * channels[2];
}

/**
 * WCAG contrast ratio between two colours.
 *
 * @param a - First colour.
 * @param b - Second colour.
 * @returns The ratio, from 1 (identical) to 21 (black on white).
 */
function contrast(a: string, b: string): number {
  const [hi, lo] = [luminance(a), luminance(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
}

/** Every surface a control or label can land on. */
const SURFACES = ["bg-0", "bg-1", "bg-2", "bg-3"] as const;

const THEMES = [
  ["dark", DARK],
  ["light", LIGHT],
] as const;

describe("token palettes", () => {
  it.each(THEMES)("%s defines every role", (_name, theme) => {
    for (const token of [
      ...SURFACES,
      "line",
      "line-2",
      "fg-0",
      "fg-1",
      "fg-2",
      "fg-3",
      "fg-dis",
      "acc",
      "acc-dim",
      "acc-deep",
      "on-acc",
      "acc-hi",
      "ok",
      "ok-deep",
      "warn",
      "err",
      "chart-down",
      "chart-up",
    ]) {
      expect(theme[token], `${token} missing`).toMatch(/^#[0-9a-f]{6}$/);
    }
  });

  it("light is a re-step, not an inversion of dark", () => {
    // If light were generated by flipping dark, the pairs would be related.
    // They are not, and the design is explicit that they must not be — this
    // catches someone "simplifying" the second palette away.
    expect(LIGHT["bg-0"]).not.toBe(DARK["bg-0"]);
    expect(LIGHT.acc).not.toBe(DARK.acc);
  });

  it("keeps the light palette in the media query and the attribute selector in sync", () => {
    // The two blocks exist because an explicit choice must beat the system
    // preference. They only work if they say the same thing.
    const media = palette(':root:not([data-theme="dark"]) {');
    for (const [token, hex] of Object.entries(LIGHT)) {
      expect(
        media[token],
        `${token} differs between the two light blocks`,
      ).toBe(hex);
    }
  });
});

/**
 * Surfaces a role is actually drawn against.
 *
 * `bg-2` and `bg-3` are the raised steps — inputs, hovered rows, an empty
 * progress track. Small labels and control borders sit on the ground and on
 * cards, not on those, so the floors below are scoped to where the role is
 * really used rather than to every surface in the palette. The pairings that
 * fall short are recorded in "known contrast gaps" instead of being quietly
 * dropped.
 */
const GROUND = ["bg-0", "bg-1"] as const;

describe("text contrast floors", () => {
  it.each(THEMES)(
    "%s: fg-3 clears 4.5:1 on the surfaces small labels sit on",
    (_name, theme) => {
      for (const surface of GROUND) {
        expect(
          contrast(theme["fg-3"], theme[surface]),
          `fg-3 on ${surface}`,
        ).toBeGreaterThanOrEqual(4.5);
      }
    },
  );

  it.each(THEMES)(
    "%s: every ink above the floor clears it on every surface",
    (_name, theme) => {
      for (const ink of ["fg-0", "fg-1", "fg-2"] as const) {
        for (const surface of SURFACES) {
          expect(
            contrast(theme[ink], theme[surface]),
            `${ink} on ${surface}`,
          ).toBeGreaterThanOrEqual(4.5);
        }
      }
    },
  );

  it.each(THEMES)(
    "%s: fg-dis stays below the floor, so it can never be used for real text",
    (_name, theme) => {
      // Asserted as an upper bound on purpose. If someone "fixes" fg-dis by
      // lightening it until it passes, it stops being visibly disabled and
      // starts being mistaken for something you can read and act on.
      for (const surface of SURFACES) {
        expect(
          contrast(theme["fg-dis"], theme[surface]),
          `fg-dis on ${surface}`,
        ).toBeLessThan(4.5);
      }
    },
  );

  it.each(THEMES)(
    "%s: ink on an accent fill clears 4.5:1, at rest and on hover",
    (_name, theme) => {
      expect(
        contrast(theme["on-acc"], theme.acc),
        "on-acc over acc",
      ).toBeGreaterThanOrEqual(4.5);
      expect(
        contrast(theme["on-acc"], theme["acc-hi"]),
        "on-acc over acc-hi",
      ).toBeGreaterThanOrEqual(4.5);
    },
  );
});

describe("non-text contrast floors", () => {
  it.each(THEMES)(
    "%s: line-2 clears 3:1 against the surfaces a control is drawn on",
    (_name, theme) => {
      for (const surface of GROUND) {
        expect(
          contrast(theme["line-2"], theme[surface]),
          `line-2 on ${surface}`,
        ).toBeGreaterThanOrEqual(3);
      }
    },
  );

  it.each(THEMES)(
    "%s: the focus ring is visible against every surface",
    (_name, theme) => {
      for (const surface of SURFACES) {
        expect(
          contrast(theme.acc, theme[surface]),
          `focus ring on ${surface}`,
        ).toBeGreaterThanOrEqual(3);
      }
    },
  );

  it("keeps the two chart series apart from each other", () => {
    // The design's own note says these converge under tritanopia, which is why
    // download and upload are always labelled as well as coloured. All this
    // guards is that nobody collapses them to the same value and removes even
    // the hue cue.
    for (const [, theme] of THEMES) {
      expect(theme["chart-down"]).not.toBe(theme["chart-up"]);
    }
  });
});

/**
 * Pairings that fall short of the floor the design states for them.
 *
 * Measured, not guessed, and asserted as "no worse than this" so a token edit
 * that degrades one fails the build. They are raised with the designer rather
 * than corrected here — inventing a colour to close the gap would put a value
 * in the app that is in no palette, which is the thing the handoff is most
 * insistent about.
 */
const KNOWN_GAPS: ReadonlyArray<
  readonly [theme: "dark" | "light", ink: string, surface: string, at: number]
> = [
  // "fg-3 is the floor that clears 4.5:1" — true on the ground and on cards,
  // not on the raised steps.
  ["dark", "fg-3", "bg-2", 4.19],
  ["dark", "fg-3", "bg-3", 3.73],
  // "line-2 clears 3:1 everywhere".
  ["dark", "line-2", "bg-2", 2.81],
  ["dark", "line-2", "bg-3", 2.5],
  ["light", "line-2", "bg-3", 2.87],
  // Status colours used as text. The design draws the pill label in the status
  // colour itself, and on light the warm steps do not carry 11px text.
  ["light", "warn", "bg-0", 3.6],
  ["light", "warn", "bg-1", 3.83],
  ["light", "ok", "bg-0", 4.33],
];

describe("known contrast gaps", () => {
  it.each(KNOWN_GAPS)(
    "%s: %s on %s is still at least %f:1",
    (name, ink, surface, floor) => {
      const theme = name === "dark" ? DARK : LIGHT;
      expect(contrast(theme[ink], theme[surface])).toBeGreaterThanOrEqual(
        floor,
      );
    },
  );
});
